---
title : "Promise(1)"

categories :
    - javascript

tags :
    - javascript

---
  ** 모던 자바스크립트 Deep Dive 책을 읽고 정리한 포스팅이다.


자바스크립트는 비동기 처리를 위한 하나의 패턴을 콜백 함수를 사용한다.  
콜백 함수는 아래와 같은 문제가 있다.

1. 콜백 헬로 인한 가독성 저하
2. 비동기 처리 중 발생한 에러 처리 힘듬
3. 여러 개의 비동기 처리를 한 번에 처리하는 한계

**ES6** 에서는 비동기 처리를 위한 또 다른 패턴은 **Promise**를 도입하였다.

### 비동기 처리를 위한 콜백 패턴의 단점

#### 1. Callback hell

```javascript
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) console.log(JSON.parse(xhr.response));
    else console.error(xhr.status, xhr.statusText);
  };
};

get("https://jsonplaceholder.typicode.com/posts/1");
```

위 예제에서 get 함수는 서버의 응답 결과를 콘솔에 출력한다. get 함수가 서버의 응답 결과를 반환하게 하려면?

get 함수는 비동기 함수(onload 이벤트 핸들러가 비동기로 동작)이다. 비동기 함수란, **함수 내부에 비동기로 동작하는 코드를 포함한 함수**이다. (예를 들어, setTimeout 함수는 콜백 함수의 호출이 비동기로 동작하므로 비동기 함수이다.)

**비동기 함수 호출 시, 함수 내부에 비동기로 동작하는 코드가 완료되지 않아도 즉시 종료된다. 비동기 동작 코드는 비동기 함수가 종료된 후에 완료된다. 따라서 비동기 함수 내부의 비동기 동작 코드에서의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.**

```javascript
let g = 0;
setTimeout(() => {
  g = 100;
}, 0);
console.log(g); // 0
```

```javascript
const response = get("https://jsonplaceholder.typicode.com/posts/1");
console.log(response); //undefined
```

get 함수의 반환문이 생략되었으므로 암묵적으로 undefined 를 반환한다. onload 이벤트 핸들러를 get 함수가 호출할 수 없으므로 반환값을 캐치할 수 없다.

상위 스코프의 변수에 할당하는 것 또한 동작하지 않는다.

```javascript
let todos;
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) todos = JSON.parse(xhr.response);
    // (1)
    else console.error(xhr.status, xhr.statusText);
  };
};

get("https://jsonplaceholder.typicode.com/posts/1");
console.log(todos); //undefined (2)
```

처리 순서가 보장되지 않는 이유가 뭘까?

1. get 함수가 호출
2. 함수 코드 평가 과정 - get 함수 실행 컨텍스트 생성되고 call stack에 푸시된다.
3. 함수 코드 실행 과정 - xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.
4. get 함수 종료되면 callstack에서 팝되고, console.log가 호출된다.
5. console.log 실행 컨텍스트가 생성되어 스택에 푸시된다. **console.log 호출되기 직전에 load 이벤트가 발생하더라도 이벤트 핸들러는 결코 console.log 보다 먼저 실행되지 않는다.**
6. onload 이벤트 핸들러는 load 이벤트가 발생하면 일단 task queue에 저장되어 대기하다가, call stack이 비면 event loop 에 의해 call stack으로 푸시되어 실행된다.  
   따라서 이벤트 핸들러가 실행되는 시점에는 call stack이 빈상태여야 하므로 console.log가 이미 종료된 이후이다.

만약 get 함수 이후에 console.log가 100번 호출이 되어도 onload 이벤트 핸들러는 모든 console.log가 종료된 이후에 실행된다. **따라서 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.**

```javascript
get("/step1", (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
        ...
    });
  });
});
```

위와 같이 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상을 **callback hell** 이라 한다.

#### 2. 에러 처리의 한계

- try ... catch ... finally 문은 에러 처리를 구현하는 방법이다. try 코드 블록이 먼저 실행되고, 이때 try 코드 블록에서 에러가 발생하면 해당 에러는 catch 문의 err 변수로 전달되고, catch 코드 블록이 실행된다. finally 코드 블록은 에러 발생과 상관없이 반드시 한 번 실행된다.

```javascript
try {
  setTimeout(() => {
    throw new Error("error");
  }, 1000);
} catch (e) {
  console.error("error", e);
}
```

**위 에러는 catch 코드 블록에서 캐치되지 않는다**.

1. 비동기 함수인 setTimeout이 호출되면 setTimeout 함수의 실행 컨텍스트가 생성되고 call stack에 푸시되어 실행된다.
2. setTimeout은 즉시 종료되어 call stack에서 제거된다.
3. 이후, 타이머가 만료되면 setTimeout 함수의 콜백 함수는 task queue로 푸시되고 call stack이 비었을 때 event loop에 의해 call stack으로 푸시되어 실행된다.

- setTimeout 함수의 콜백 함수가 실행될 때 이미 setTimeout 함수는 call stack에서 제거된 상태이다. setTimeout 함수의 콜백 함수의 caller는 setTimeout이 아니라는 의미이다.  
  **에러는 caller 방향으로 전파된다.** 하지만, setTimeout 함수의 콜백 함수는 caller가 없다. 따라서 catch 블록에서 캐치되지 않는다.

### 프로미스의 생성

- Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는다. (resolve, reject 함수)

```javascript
const promise = new Promise((resolve, reject) => {
    if(/*비동기 처리가 성공하면*/) resolve('result');
    else reject('failure reason');
})
```

```javascript
const promiseGet = (url) => {
  //함수 내부에서 promise 생성하고 반환한다.
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) resolve(JSON.parse(xhr.response));
      else reject(new Error(xhr.status));
    };
  });
};

promiseGet("https://jsonplaceholder.typicode.com/posts/1");
```

promiseGet 은 비동기 함수로 함수 내부에서 프로미스를 생성하고 반환한다. 만약 비동기 처리가 성공하면 비동기 처리 결과를 resolve 함수에 인수로 전달하면서 호출하고, 비동기 처리가 실패하면 에러를 reject 함수에 인수로 전달하면서 호출한다.

- Promise 의 상태 정보

  - pending, 비동기 처리가 아직 수행되지 않은 상태. 상태 변경 조건 : 프로미스가 생성된 직후 기본 상태
  - fulfilled, 비동기 처리가 수행된 상태(settled, 성공). 상태 변경 조건 : resolve 함수 호출
  - rejected, 비동기 처리가 수행된 상태(settled, 실패). 상태 변경 조건 : reject 함수 호출

- 생성된 직후의 프로미스는 기본적으로 pending 상태이다. 이후 비동기 처리 결과에 따라 fulfilled, rejected 상태로 변경된다.
- **프로미스 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.**
- pending 상태에서는 settled 상태로 변경 가능하다. 그러나, settled 상태에서는 다른 상태로 변화할 수 없다.

```javascript
const fulfilled = new Promise((resolve) => resolve(1));
const rejected = new Promise((_, reject) => reject(new Error("error occured")));
```

- **Promise는 비동기 처리 상태와 처리 결과를 관리하는 객체이다.**

### 프로미스의 후속 처리 메소드

- then, catch, finally 가 있다.
- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메소드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.
- **항상 프로미스를 반환**하며, 비동기로 동작한다. 콜백 함수가 프로미스를 반환하면 그대로 반환하고, 다른 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환한다.

1. Promise.prototype.then

   - 두 개의 콜백 함수를 인자로 받는다. 첫 번째 콜백 함수는 비동기 처리가 성공(resolve 함수가 호출되었을 때)했을 때 호출되는 함수, 두 번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 함수이다.

   ```javascript
   new Promise((resolve) => resolve("fulfilled")).then(
     (v) => console.log(v),
     (e) => console.error(e)
   ); //fulfilled

   new Promise((_, reject) => reject(new Error("rejected"))).then(
     (v) => console.log(v),
     (e) => console.error(e)
   ); //Error : rejected
   ```

2. Promise.prototype.catch

   - 한 개의 콜백 함수를 인자로 받는다. 이 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.
   - then(undefined, onRejected) 와 동일하게 동작한다.

   ```javascript
   new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>
     console.log(e)
   ); // Error : rejected

   new Promise((_, reject) => reject(new Error("rejected"))).then(
     undefined,
     (e) => console.error(e)
   ); //Error : rejected
   ```

3. Promise.prototype.finally

   - 한 개의 콜백 함수를 인자로 받는다. 이 콜백 함수는 프로미스의 성공과 실패에 상관없이 무조건 한 번 호출된다.

   ```javascript
   new Promise(() => {}).finally(() => console.log("finally")); // finally
   ```

```javascript
const promiseGet = (url) => {
  //함수 내부에서 promise 생성하고 반환한다.
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) resolve(JSON.parse(xhr.response));
      else reject(new Error(xhr.status));
    };
  });
};

promiseGet("https://jsonplaceholder.typicode.com/posts/1")
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log("Bye"));
```

### 프로미스의 에러 처리

- then 메소드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 가독성이 떨어지므로, **catch 메소드 사용을 권장**한다.
- catch 메소드는 모든 then 메소드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러(rejected 상태)뿐만 아니라, then 메소드 내부에서 발생한 에러까지도 모두 캐치할 수 있다.

```javascript
promiseGet("https://jsonplaceholder.typicode.com/posts/1")
  .then((res) => console.xxx(res))
  .catch((err) => console.error(err)); //TypeError : console.xxx is not a function
```

### Promise Chaining

```javascript
const url = "https://jsonplaceholder.typicode.com";
promiseGet(`${url}/posts/1`)
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

- then -> then -> catch 순서로 후속 처리 메소드를 호출했다. 이 메소드는 언제나 프로미스를 반환하므로 연속적으로 호출이 가능하다. 이를 Promise chanining 이라 한다.
- 후속 처리 메소드의 콜백 함수는 프로미스의 비동기 처리 상태가 변경되면 선택적으로 호출된다.

1. 첫 번째 then
   - 인수 : promiseGet 함수가 반환한 프로미스가 resolve한 값(id가 1인 포스트)
   - 반환값 : 콜백 함수가 반환한 프로미스
2. 두 번째 then
   - 인수 : 첫 번째 then 이 반환한 프로미스가 resolve한 값
   - 반환값 : 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스
3. catch
   - 인수 : promiseGet 함수 또는 앞선 후속 처리 메소드가 반환한 프로미스가 reject 한 값
   - 반환값 : 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스

- 프로미스도 콜백 패턴을 사용하므로, 콜백 함수를 사용한다. 다만 콜백 헬이 발생하지 않을 뿐이다.
- 콜백 패턴은 가독성이 좋지 않다 -> ES8에서 도입된 async/await 로 해결한다.
